### ISSUE TITLE
Worse FPS compared to GPU plugin

### ISSUE THREAD

**Issue by f0rmatme** [Runemoro/better-renderer#3]
Worse FPS then GPU plugin, anyway to make the plugin maybe utilize more of the gpu and if that happens
Couldn't you unlimit the cameras fps in the render to support 144hz + screens?
I remember seeing a jagex post saying something about that

**Comment by Runemoro** [comment]
I'm confused by what you're referring to.

Your first sentence makes it seem like it's lagging and FPS it too low. In that case, are you comparing with the GPU at the same max render distance of 90 tiles (not the plugin default of 250)?

Your second sentence makes it seem like it's being limited to a too small refresh rate (ex. 60 instead of 144).

What FPS are you getting with GPU vs. with the plugin?

**Comment by Runemoro** [comment]
Closing this since there's not enough details.
